version: '3.4'

services:
  musicmanager:
    image: musicmanager:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: musicmanager-debug
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 8080"]
    ports:
      - 8080:8080
      - 5678:5678
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      # Zuf채llige Zeichenkette, die als Schl체ssel f체r die Verschl체sselung verwendet wird
      - SECRET_KEY=e7*hZJA5HUowceuPZwbXYH8fe%ajhp

